export const DOMAINS = [
  "admin",
  "clinic",
  "public",
  "particular",
  "platform",
  "regression",
] as const;

export const CURRENT_COHORTS = [
  "smoke",
  "admin-mobile",
  "visual-contract",
  "public-clinic",
] as const;

export const EXECUTION_COHORTS = [
  "ci",
  "extended",
  "evidence",
  "visual-linux",
  "full",
  "affected",
] as const;

export const PLATFORMS = ["any", "linux"] as const;

// What an entry's assertions actually traverse. Every spec drives the real
// Next.js app, and the only backend Playwright starts is the hermetic fixture
// API (e2e/fixtures/admin-populated-api-server.mjs).
// - mocked: at least one response the spec depends on is fabricated by
//   route.fulfill in the spec or in a helper it calls.
// - fixture: nothing is fabricated; backend traffic, if any, reaches only the
//   fixture API (a request rewritten towards the fixture still counts).
// - integration: reaches the real Fastify server and/or Postgres.
export const LAYERS = ["mocked", "fixture", "integration"] as const;

export type E2eDomain = (typeof DOMAINS)[number];
export type E2eCurrentCohort = (typeof CURRENT_COHORTS)[number];
export type E2eExecutionCohort = (typeof EXECUTION_COHORTS)[number];
export type E2ePlatform = (typeof PLATFORMS)[number];
export type E2eLayer = (typeof LAYERS)[number];
export type E2eCriticality = "P0" | "P1" | "P2" | "P3";
export type E2eTargetGate = "current-ci" | "future-p1" | "extended" | "manual";

export type E2eCatalogEntry = {
  readonly path: `e2e/${string}.spec.ts`;
  readonly domain: E2eDomain;
  readonly feature: string;
  readonly contractType: string;
  readonly layer: E2eLayer;
  readonly proves: string;
  readonly criticality: E2eCriticality;
  readonly owner: string;
  readonly currentCohorts: readonly E2eCurrentCohort[];
  readonly executionCohorts: readonly E2eExecutionCohort[];
  readonly platform: E2ePlatform;
  readonly fixture: string;
  readonly evidence: string;
  readonly targetGate: E2eTargetGate;
  readonly notes: string;
};

const ci = ["ci", "full"] as const;
const extended = ["extended", "full"] as const;
const evidence = ["evidence", "full"] as const;
const visualLinux = ["visual-linux", "full"] as const;

const entry = (
  path: E2eCatalogEntry["path"],
  domain: E2eDomain,
  feature: string,
  contractType: string,
  currentCohorts: readonly E2eCurrentCohort[],
  executionCohorts: readonly E2eExecutionCohort[],
  layer: E2eLayer,
  proves: string,
  options: Partial<
    Pick<
      E2eCatalogEntry,
      "criticality" | "platform" | "fixture" | "evidence" | "targetGate" | "notes"
    >
  > = {},
): E2eCatalogEntry => ({
  path,
  domain,
  feature,
  contractType,
  layer,
  proves,
  criticality: options.criticality ?? (currentCohorts.length > 0 ? "P1" : "P2"),
  owner: domain,
  currentCohorts,
  executionCohorts,
  platform: options.platform ?? "any",
  fixture: options.fixture ?? "none",
  evidence: options.evidence ?? "none",
  targetGate: options.targetGate ?? (currentCohorts.length > 0 ? "current-ci" : "extended"),
  notes: options.notes ?? "",
});

export const E2E_SUITE_CATALOG = [
  entry("e2e/admin/clinics/admin-clinic-edit-drawer.spec.ts", "admin", "clinics", "admin isolation edit drawer", ["admin-mobile"], ci, "mocked", "Against route-stubbed GET/PATCH /api/admin/clinics responses: the edit drawer opens with the row's data, passwords stay hidden until an explicit reveal, cancel and Escape close without saving, save sends the PATCH, a stubbed 400 is shown inside the drawer and search/pagination survive opening it; plus a Node-only source check that ClinicEditDrawer imports no backend or middleware module.", { criticality: "P1", notes: "Security isolation contract; do not demote." }),
  entry("e2e/admin/clinics/admin-clinics-mobile-card-layout.spec.ts", "admin", "clinics", "mobile card layout", ["admin-mobile"], ci, "mocked", "With a route-stubbed /api/admin/clinics dataset, admin Clínicas mobile cards stay operable at each mobile viewport and pagination advances through adaptive pages."),
  entry("e2e/admin/pricing/admin-pricing-multi-form-measurement.spec.ts", "admin", "pricing", "multi-form measurement", [], extended, "mocked", "With route-stubbed /api/admin/pricing data, a taller errored non-first pricing form keeps the adaptive pager visible and no form is clipped."),
  entry("e2e/admin/shell/admin-mobile-app-shell-absolute-no-scroll.spec.ts", "admin", "shell", "absolute no-scroll app shell", ["admin-mobile"], ci, "fixture", "With the populated fixture admin session, the admin mobile app shell has no document, body or main scroll at each mobile viewport and at a landscape diagnostic viewport."),
  entry("e2e/admin/shell/admin-mobile-bottom-navigation-no-scroll.spec.ts", "admin", "shell", "bottom navigation no-scroll", ["admin-mobile"], ci, "fixture", "With the populated fixture admin session, the admin bottom navigation is complete and scroll-free at each mobile viewport, and desktop keeps the lateral navigation and desktop actions."),
  entry("e2e/admin/shell/admin-mobile-config-modules-no-scroll.spec.ts", "admin", "shell", "config modules no-scroll", ["admin-mobile"], ci, "mocked", "Admin mobile config modules are scroll-free at each mobile viewport in light and dark and keep their 1280x800 desktop layout; pricing, schema-health and maintenance purge-dry-run responses are route-stubbed.", { evidence: "test-results" }),
  entry("e2e/admin/shell/admin-mobile-core-modules-no-scroll.spec.ts", "admin", "shell", "core modules no-scroll", ["admin-mobile"], ci, "mocked", "Admin mobile core modules are scroll-free at each mobile viewport, reachable from the bottom nav and the Más menu, reports pagination advances with a bottom-anchored pager and desktop keeps each layout at 1280x800; clinics, report-workflow and particular-tokens responses are route-stubbed.", { fixture: "admin-mobile-contracts" }),
  entry("e2e/admin/shell/admin-mobile-final-polish-no-scroll.spec.ts", "admin", "shell", "final polish no-scroll", ["admin-mobile"], ci, "mocked", "Closeout geometry of the admin mobile shell at each mobile viewport plus a 1280x800 desktop smoke, with clinics and sessions responses route-stubbed.", { fixture: "admin-mobile-contracts", evidence: "test-results" }),
  entry("e2e/admin/shell/admin-mobile-hub-launcher-no-scroll.spec.ts", "admin", "shell", "hub launcher no-scroll", ["admin-mobile"], ci, "fixture", "With the populated fixture admin session, the admin mobile hub is a paginated scroll-free launcher with borderless larger-icon tiles, and desktop keeps the lateral navigation without the mobile launcher."),
  entry("e2e/admin/shell/admin-mobile-hub-stale-layer-stage.spec.ts", "admin", "shell", "stale layer stage", ["admin-mobile"], ci, "fixture", "With the populated fixture admin session, the admin mobile hub keeps one persistent isolated stage across the hub/module swap in every width x height x mode cell.", { evidence: "test-results" }),
  entry("e2e/admin/shell/admin-mobile-module-layer-isolation.spec.ts", "admin", "shell", "module layer isolation", ["admin-mobile"], ci, "mocked", "Admin mobile modules keep isolated paint layers at each mobile viewport and the hub keeps an opaque paint chain after visiting tokens; /api/admin/sessions is route-stubbed.", { evidence: "test-results" }),
  entry("e2e/admin/shell/admin-mobile-ops-modules-no-scroll.spec.ts", "admin", "shell", "ops modules no-scroll", ["admin-mobile"], ci, "mocked", "Admin mobile ops modules have no scroll at each mobile viewport, keep their 1280x800 desktop layout and the sessions Tipo/Estado selects render uncut option text; sessions and users-roles responses are route-stubbed.", { fixture: "admin-mobile-contracts" }),
  entry("e2e/admin/shell/admin-mobile-status-modules-no-scroll.spec.ts", "admin", "shell", "status modules no-scroll", ["admin-mobile"], ci, "mocked", "Admin mobile status modules are scroll-free at each mobile viewport in light and dark, keep their 1280x800 desktop layout and the Alertas chip paginates failed-login alerts by measured fit; failed-login-alerts and schema-health responses are route-stubbed.", { fixture: "admin-mobile-contracts", evidence: "test-results" }),
  entry("e2e/admin/tokens/admin-tokens-mobile-toolbar-layout.spec.ts", "admin", "tokens", "mobile toolbar layout", ["admin-mobile"], ci, "mocked", "Admin tokens mobile toolbar stays operable per viewport, the mobile pager stays bottom-anchored with full and short datasets, the create dialog uses linked-clinic search and the initial window keeps two complete adaptive pages across the canonical matrix; particular-tokens and users-roles responses are route-stubbed."),
  entry("e2e/admin/users/admin-users-fixture-pagination.spec.ts", "admin", "users", "fixture pagination", [], extended, "fixture", "The fixture API itself, not the production endpoint: /api/admin/users-roles serves a deterministic 5000-user dataset that caps oversized limits and honors offset, userType, role, query/search and status.", { fixture: "admin-populated-api-server" }),
  entry("e2e/admin/users/admin-users-roles-pager-reachability.spec.ts", "admin", "users", "pager reachability under adaptive geometry", [], extended, "fixture", "Over the fixture's high-volume users-roles dataset (browser GETs rewritten to dataset=high-volume), 1280x720 adapts the rows and keeps the pager clickable, and the other desktop viewports keep nine populated rows.", { criticality: "P1", fixture: "admin-populated-api-server", notes: "A03 PASS 3 regression: the adaptive desktop row floor must keep the pager reachable." }),
  entry("e2e/admin/users/admin-users-visual-quality-gate.spec.ts", "admin", "users", "visual quality capacity", [], extended, "fixture", "Over the fixture's high-volume users-roles dataset (request rewrite), measured desktop and mobile metrics (select clipping, text contrast, table, row and pager geometry) meet the gate thresholds at 1440x900, 1366x768, 390x844, 360x740 and 430x932.", { fixture: "admin-mobile-contracts", notes: "Audit CAP classification mapped to extended in E2E-ORG-1." }),
  entry("e2e/admin/users/admin-users-workspace-5000.spec.ts", "admin", "users", "workspace capacity 5000", [], extended, "fixture", "Over the fixture's 5000-user dataset (request rewrite), the admin users-roles workspace renders a bounded first slice with coherent totals, paginates forward and back, keeps totals coherent under userType/role filters and preserves the no-scroll app shell.", { notes: "Audit CAP classification mapped to extended in E2E-ORG-1." }),
  entry("e2e/admin/users/admin-users-workspace-mobile-5000.spec.ts", "admin", "users", "mobile workspace capacity 5000", [], extended, "fixture", "Over the fixture's 5000-user dataset (request rewrite) on mobile, the workspace renders a bounded slice with coherent totals, AdminMobileOpsPager goes forward and back without rendering the whole dataset, userType/role filters stay coherent and each viewport keeps the no-scroll shell with item fit.", { fixture: "admin-mobile-contracts", notes: "Audit CAP classification mapped to extended in E2E-ORG-1." }),
  entry("e2e/clinic/logistics/dashboard-clinic-logistica-mobile-parity.spec.ts", "clinic", "logistics", "mobile logistics parity", ["public-clinic"], ci, "fixture", "With the populated fixture clinic session, Clinic Logística measured against itself (no Admin session, not a parity comparison) at 360x740, 390x844 and 430x932: no overflow, adaptive rows, navigation structure and dialog content with a long visit address."),
  entry("e2e/clinic/logistics/dashboard-logistica-metricas-full-route-adaptive.spec.ts", "clinic", "logistics", "metrics full route adaptive", [], extended, "fixture", "With the populated fixture clinic session, the Logística Métricas full route renders an always-visible pager sized per viewport without external scroll, aggregates metrics from the visible page only and navigates next/previous keeping the offset in the URL."),
  entry("e2e/clinic/logistics/dashboard-logistica-mobile-action-bar-reachability.spec.ts", "clinic", "logistics", "mobile bottom chrome reachability", [], extended, "fixture", "With the populated fixture clinic session, the logistics hub header actions and every row are hit-testable (not merely visible) above the role bottom nav at each mobile viewport and at the md boundary.", { criticality: "P1", fixture: "admin-populated-api-server", notes: "Hit-testability (not visibility) of the hub pagers and the StickyActionBar actions under the role bottom nav; 5 mobile viewports + the md boundary." }),
  entry("e2e/clinic/logistics/dashboard-logistica-rutas-full-route-adaptive.spec.ts", "clinic", "logistics", "routes full route adaptive", [], extended, "fixture", "With the populated fixture clinic session, the Logística Rutas full route renders an always-visible pager sized per viewport without external scroll and navigates next/previous keeping the offset in the URL."),
  entry("e2e/clinic/logistics/dashboard-logistica-visitas-full-route-adaptive.spec.ts", "clinic", "logistics", "visits full route adaptive", [], extended, "fixture", "With the populated fixture clinic session, the Logística Visitas full route renders an always-visible pager sized per viewport without external scroll and navigates next/previous keeping the offset in the URL."),
  entry("e2e/clinic/logistics/logistics-mobile-no-horizontal-table.spec.ts", "clinic", "logistics", "mobile no horizontal table", [], extended, "fixture", "With the populated fixture clinic session, each logistics full route renders mobile rows with no horizontal table scroll at each mobile viewport."),
  entry("e2e/clinic/profile/dashboard-clinic-perfil-mobile-operability.spec.ts", "clinic", "profile", "mobile profile operability", ["public-clinic"], ci, "mocked", "With a synthetic clinic session cookie and a route-stubbed /api/clinic/profile, the public profile editor stays operable at 360x740, 390x844 and 430x932."),
  entry("e2e/clinic/reports/clinic-informes-zero-internal-scroll.spec.ts", "clinic", "reports", "internal no-scroll", [], extended, "fixture", "With the populated fixture clinic session, the Informes full route has no core internal scroller and a bounded detail at each viewport, and detail sections switch without introducing scroll."),
  entry("e2e/clinic/reports/clinic-reports-fixture-pagination.spec.ts", "clinic", "reports", "fixture pagination", [], extended, "fixture", "The fixture API itself, not the production endpoint: /api/reports and /api/reports/search serve a deterministic 1000-report dataset honoring status, studyType, query, limit and offset, and the /dashboard informes summary still receives only 3 recent reports.", { fixture: "admin-populated-api-server" }),
  entry("e2e/clinic/reports/clinic-reports-workspace-1000.spec.ts", "clinic", "reports", "workspace capacity 1000 with P1 guards", [], extended, "fixture", "Over the fixture's 1000-report dataset, the clinic reports workspace renders a bounded first slice, paginates to a later page and keeps limit/offset and totalPages coherent under status, query and studyType filters.", { notes: "Known Informes product defect remains out of scope; audit CAP classification mapped to extended." }),
  entry("e2e/clinic/reports/dashboard-clinic-informes-mobile-parity.spec.ts", "clinic", "reports", "mobile reports parity", ["public-clinic"], ci, "fixture", "With the populated fixture clinic session, Clinic Informes measured against itself (no Admin session, not a parity comparison) at 360x740, 390x844 and 430x932: populated mobile layout with adaptive row capacity and a long patient name, and the painted table head charged to row capacity."),
  entry("e2e/clinic/reports/dashboard-informes-server-adaptive-pagination.spec.ts", "clinic", "reports", "server adaptive pagination", [], extended, "fixture", "With the populated fixture clinic session, the Informes full route shows an always-visible pager sized per viewport without external scroll, swaps rows with an in-sync page indicator and no longer paginates through a URL page parameter."),
  entry("e2e/clinic/shell/clinic-mobile-admin-parity-contract.spec.ts", "clinic", "shell", "CMP-12 cross-role runtime parity contract", ["public-clinic"], ci, "fixture", "Admin and Clinic populated fixture sessions measured in the same run and compared to each other on 10 clinic mobile surfaces x 6 canonical phone viewports.", { fixture: "admin-populated-api-server", notes: "CMP-12/RC-017: all 10 clinic mobile surfaces × 6 canonical phone viewports, measuring Admin and Clinic in the same run and comparing them to each other — the contract that closes the enabling root cause of the 42 audited differences." }),
  entry("e2e/clinic/shell/dashboard-adaptive-rows.spec.ts", "clinic", "shell", "adaptive rows", [], extended, "fixture", "With the populated fixture clinic session, the Informes full route page size grows from 390x844 to 1440x900, the Informes workspace summary is not pinned to 3 rows at 1440x900 and the Logística summary paginates with adaptive rows and a pager."),
  entry("e2e/clinic/shell/dashboard-centered-pager.spec.ts", "clinic", "shell", "centered pager", [], extended, "fixture", "With the populated fixture clinic session, each listed surface renders its pager as a visible centered cluster (within 40px of the surface center), not a right-aligned footer."),
  entry("e2e/clinic/shell/dashboard-clinic-controller-workspace-parity.spec.ts", "clinic", "shell", "controller rail workspace parity", [], extended, "fixture", "With synthetic clinic/admin session cookies, clinic /dashboard opens the default workspace without a hub, ?module= deep links load each workspace, the full routes and the admin hub still load, lateral nav switches keep the stage and a visible aria-current, the command center Estado tab exposes its blocks, and 390x844 has no horizontal overflow or main scroll."),
  entry("e2e/clinic/shell/dashboard-clinic-full-route-stage-parity.spec.ts", "clinic", "shell", "CMP-06 full-route module stage parity", ["public-clinic"], ci, "fixture", "With synthetic clinic/admin session cookies, 5 clinic full routes x 6 canonical phone viewports compare the stage/workspace/viewport/module-card frame against the Admin frame measured at runtime.", { fixture: "admin-populated-api-server", notes: "CMP-06: 5 clinic full routes × 6 canonical phone viewports compare the complete stage/workspace/viewport/module-card frame against live Admin runtime." }),
  entry("e2e/clinic/shell/dashboard-clinic-metric-run-parity.spec.ts", "clinic", "shell", "CMP-05 canonical metric run parity", ["public-clinic"], ci, "fixture", "With a synthetic clinic session cookie, 10 clinic surfaces x 6 canonical phone viewports render the single inline ModuleMetricRun implementation.", { fixture: "admin-populated-api-server", notes: "CMP-05: 10 clinic surfaces × 6 canonical phone viewports verify the one inline ModuleMetricRun implementation." }),
  entry("e2e/clinic/shell/dashboard-clinic-mobile-content-reachability.spec.ts", "clinic", "shell", "mobile content reachability", [], extended, "fixture", "With the populated fixture clinic session, the last Operaciones card at 360x640 and the last Perfil section at 375x667 are reachable without horizontal overflow or double scroll, 390x844 stays stable and 1366x768 main/body/html gain no scroll."),
  entry("e2e/clinic/shell/dashboard-clinic-mobile-operational-density.spec.ts", "clinic", "shell", "mobile operational density", [], extended, "fixture", "With the populated fixture clinic session, mobile Informes, Logística, Perfil and Tokens drop the redundant header and keep compact CTAs without horizontal overflow; mobile chrome is not selectable while form fields stay editable, pinch-zoom stays available and 1280x800 desktop is unaffected."),
  entry("e2e/clinic/shell/dashboard-clinic-module-card-parity.spec.ts", "clinic", "shell", "CMP-04 canonical module card parity", ["public-clinic"], ci, "fixture", "With a synthetic clinic session cookie, 5 clinic root modules x 6 canonical phone viewports expose one canonical ModuleCard with zero page overflow.", { fixture: "admin-populated-api-server", notes: "CMP-04: 5 clinic root modules × 6 canonical phone viewports verify the shared ModuleCard geometry and zero page overflow." }),
  entry("e2e/clinic/shell/dashboard-clinic-module-state-parity.spec.ts", "clinic", "shell", "module state parity", [], extended, "mocked", "Clinic module states: Operaciones, Informes and Logística SSR load errors (sessions against the fixture) show retry controls instead of empty states and fit 390x844, while Tokens and Perfil loading/empty/error/retry and cambiar-contraseña resubmit states are driven by route-stubbed particular-tokens, study-tracking, clinic/profile and auth/change-password responses."),
  entry("e2e/clinic/shell/dashboard-interaction-foundation.spec.ts", "clinic", "shell", "interaction foundation", ["smoke"], ci, "fixture", "With synthetic clinic/admin session cookies, clinic /dashboard opens the default Operaciones workspace without a hub, lateral and mobile navigation expose every module, ?module= deep links and rail switches update the workspace (also under reduced motion), and admin ?hub=1 and ?module=admin-clinics render with the Volver button contract."),
  entry("e2e/clinic/shell/dashboard-master-detail-state-polish.spec.ts", "clinic", "shell", "master-detail state polish", ["visual-contract"], ci, "fixture", "With a synthetic clinic session cookie, Informes renders its reports list, inline (not lateral) detail and compact filter region without a table-based master-detail and without horizontal overflow at 768px and 375px."),
  entry("e2e/clinic/shell/remove-dashboard-home-unified-workspace.spec.ts", "clinic", "shell", "post hub removal behavior", [], extended, "fixture", "With a synthetic clinic session cookie, /dashboard renders no home/hub/tile grid and resolves to Operaciones marked active, ?module= deep links open each workspace, the lateral navigation lists all 5 modules, the five-slot mobile model reaches every module and there is no external or horizontal scroll per viewport."),
  entry("e2e/clinic/tokens/dashboard-clinic-tokens-mobile-parity.spec.ts", "clinic", "tokens", "mobile tokens parity", ["public-clinic"], ci, "mocked", "Clinic Tokens measured against itself (no Admin session, not a parity comparison) at four phone viewports with route-stubbed /api/particular-tokens and /api/study-tracking: toolbar geometry against the literal labels, a tracking error kept with the token that produced it, and deliberate token wizard actions."),
  entry("e2e/particular/auth/particular-authenticated-no-scroll.spec.ts", "particular", "auth", "authenticated no-scroll", [], extended, "mocked", "With route-stubbed /api/particular/auth/me and study-tracking/me (the session cookie is only documentary), the authenticated /particulares state holds the no-scroll contract across the zoom matrix and height boundaries for available and pending reports, keeps actions and logout reachable with max-length metadata, activates exactly one declared scroll owner when height is insufficient, and a route-stubbed logout restores the public flow; plus a Node-only check that schema varchar limits stay pinned.", { fixture: "particular-session-contracts", notes: "Matriz completa de zoom (viewport CSS reducido) x report available/pending, mas las fronteras de altura 833/832/816/815 y el regimen de scroll owner declarado. El minimo que bloquea merges vive en particular-authenticated-zoom-sentinel.spec.ts (cohorte ci)." }),
  entry("e2e/particular/auth/particular-authenticated-session-fixture.spec.ts", "particular", "auth", "authenticated session fixture", [], extended, "mocked", "With route-stubbed /api/particular/auth/me and study-tracking/me, /particulares renders the authenticated token-gated state and stays free of horizontal overflow and forbidden internal scroll at 390x844.", { fixture: "particular-session-contracts" }),
  entry("e2e/particular/auth/particular-authenticated-zoom-sentinel.spec.ts", "particular", "auth", "authenticated zoom sentinel", ["public-clinic"], ci, "mocked", "With route-stubbed particular session responses at 1536x696 and report=null/reception, the marketing layer is hidden, logout stays reachable and nothing clips against the clipping ancestor.", { criticality: "P1", fixture: "particular-session-contracts", notes: "Sentinel required: desktop short-height 1536x696 con report=null/reception, marketing oculto, logout alcanzable y cero clipping contra el ancestro recortador." }),
  entry("e2e/platform/accessibility/accessibility-axe-key-routes.spec.ts", "platform", "accessibility", "axe key routes", [], extended, "fixture", "axe reports no violations on the key public, login and dashboard routes (dashboards with populated fixture sessions) at each tested viewport."),
  entry("e2e/platform/accessibility/dashboard-accessibility-keyboard.spec.ts", "platform", "accessibility", "dashboard keyboard accessibility", ["visual-contract"], ci, "mocked", "With synthetic session cookies and route-stubbed admin particular-tokens, study-tracking and users-roles responses, Informes filters, report actions, the notifications panel and the admin hub expose accessible roles and labels, and a hub card activates its workspace via Enter."),
  entry("e2e/platform/app-shell/dashboard-app-shell-visibility-contract.spec.ts", "platform", "app-shell", "app shell visibility", ["visual-contract"], ci, "mocked", "At 1366x650 and 1280x650, with synthetic session cookies and route-stubbed clinic profile, admin clinics, sessions and pricing responses, the clinic and admin dashboards expose the visible App Shell release contract."),
  entry("e2e/platform/app-shell/dashboard-card-navigation-shell.spec.ts", "platform", "app-shell", "navigation and deep links", ["visual-contract"], ci, "fixture", "With synthetic session cookies: default clinic workspace without hub, rail and lateral-nav switching, admin hub cards and workspace activation, deep links with invalid ?module= fallback, Back/Forward, workspace isolation, no global scroll, and a pre-hydration click that navigates exactly once (JS delivery delayed via route.continue, nothing stubbed); plus two Node-only source import checks."),
  entry("e2e/platform/app-shell/dashboard-detail-text-integrity.spec.ts", "platform", "app-shell", "detail text integrity", ["visual-contract"], ci, "mocked", "Admin and clinic detail/dialog surfaces render long synthetic clinical values in full with no hidden glyphs; the long records come partly from the fixture long-text dataset and partly from route-stubbed particular-tokens, report-workflow, failed-login-alerts and users-roles responses.", { criticality: "P1", fixture: "admin-populated-api-server", notes: "PR-TRUNC: DETAIL/DIALOG surfaces must render clinical values in full; long synthetic strings, admin + clinic." }),
  entry("e2e/platform/app-shell/dashboard-global-masked-master-detail.spec.ts", "platform", "app-shell", "masked master detail", ["visual-contract"], ci, "mocked", "At 1366x768 and 390x844, with synthetic session cookies and route-stubbed particular-tokens and study-tracking, the migrated modules keep main/body/html free of operational scroll and the clinic Tokens alta and detail dialogs open without turning main into a scroll container."),
  entry("e2e/platform/app-shell/dashboard-internal-no-scroll-contract.spec.ts", "platform", "app-shell", "internal no-scroll", ["visual-contract"], ci, "fixture", "With synthetic session cookies, main.dashboard-main is not an overflow-y auto/scroll container and main/body/html do not scroll on the principal admin and clinic shells at 1366x768 and 390x844."),
  entry("e2e/platform/app-shell/dashboard-mobile-shell-nav-contract.spec.ts", "platform", "app-shell", "mobile shell navigation", ["visual-contract"], ci, "fixture", "With synthetic session cookies, each listed clinic and admin dashboard route keeps its mobile shell and navigation usable at five phone viewports from 360x740 to 430x932."),
  entry("e2e/platform/app-shell/dashboard-real-app-shell-no-scroll-contract.spec.ts", "platform", "app-shell", "real app shell no-scroll", ["visual-contract"], ci, "mocked", "Dashboard routes fit each viewport without external or internal scroll with dense route-stubbed clinic profile, clinics, sessions and pricing snapshots, the perfil editor tabs fit, and the admin audit mobile filter stays hydration-safe for keyboard input."),
  entry("e2e/platform/app-shell/dashboard-single-viewport-app-shell.spec.ts", "platform", "app-shell", "single viewport app shell", ["visual-contract"], ci, "fixture", "With synthetic session cookies, desktop dashboard modules fit one viewport at 1440x900 and 1366x768 with no document scroll and main scrollHeight not exceeding clientHeight."),
  entry("e2e/platform/app-shell/dashboard-viewport-zoom-adaptability.spec.ts", "platform", "app-shell", "viewport zoom adaptability", ["visual-contract"], ci, "mocked", "No html/body/main scroll across real and zoom-effective viewports, page padding and the master/detail panel floor shrink with effective height, the clinic Tokens and particular token gate baselines fit and the admin Auditoría pager stays operable; particular-tokens and a 401 particular/auth/me are route-stubbed."),
  entry("e2e/platform/app-shell/dashboard-workspace-layout-polish.spec.ts", "platform", "app-shell", "workspace layout polish", ["visual-contract"], ci, "fixture", "With synthetic session cookies, clinic and admin workspaces open with the enter class, /dashboard/informes loads, the Volver button contract holds, the clinic workspace has no Vista general control, reduced motion keeps the workspace visible, the shell keeps h-dvh overflow-hidden and each route keeps a contained frame inset."),
  entry("e2e/platform/app-shell/dashboard-zero-scroll-mobile-boundary.spec.ts", "platform", "app-shell", "mobile zero-scroll boundary", [], extended, "fixture", "With populated fixture sessions, clinic routes keep their content inside the viewport and /dashboard/admin keeps its content above the bottom nav at the lower mobile boundary viewports."),
  entry("e2e/platform/auth/dashboard-admin-boundary-cross-role.spec.ts", "platform", "auth", "cross-role admin boundary rejection (simulated)", ["smoke"], ci, "fixture", "A clinic-only session cookie requesting /dashboard/admin is redirected to /login by the unmodified proxy.ts cookie-name gate; neither Fastify nor Postgres is involved.", { criticality: "P1", notes: "E2E-GLOBAL-03 (LIMPIEZA E2E P0-1/R-01/B-3): a clinic-only session is redirected to /login when it requests /dashboard/admin. Exercises the real, unmodified proxy.ts cookie-presence gate; does not start server/** or Postgres. E2E-GLOBAL-03B closes the authoritative Fastify boundary. Security boundary; do not demote." }),
  entry("e2e/platform/auth/dashboard-auth-redirect.spec.ts", "platform", "auth", "unauthenticated private route redirects to /login with next", ["smoke"], ci, "fixture", "With no session cookie, /dashboard, /dashboard/admin and /dashboard/informes redirect to /login?next=<path>, render the login form without 401/Unauthorized text, stay on /login and raise no page errors; no backend call, no admin 404 and no cross-role case.", { criticality: "P1", notes: "Security boundary; do not demote." }),
  entry("e2e/platform/auth/dashboard-logout-private-cache.spec.ts", "platform", "auth", "logout endpoint call and non-public private cache", ["smoke"], ci, "mocked", "Cerrar sesión requests the role logout endpoint (route-stubbed, so server-side session invalidation is NOT verified) and lands on /login; after the test itself clears cookies, the dashboard redirects to /login; authenticated dashboard documents are no-cache and not public (no-store is not asserted here).", { criticality: "P1", targetGate: "current-ci", notes: "Security boundary promoted to the effective CI gate in E2E-ORG-CI; do not demote." }),
  entry("e2e/platform/auth/dashboard-session-boundary-unauthorized.spec.ts", "platform", "auth", "expired session -> 401 -> login redirect (simulated)", ["smoke"], ci, "fixture", "The fixture answers 401 for a recognized-but-expired clinic session on every getDashboardStats path, and the clinic dashboard turns that 401 into a /login redirect; simulated fixture boundary, not Fastify.", { criticality: "P1", fixture: "admin-populated-api-server", notes: "E2E-GLOBAL-03 (LIMPIEZA E2E P0-1/R-01, caso c): admin-populated-api-server.mjs answers 401 for a new, additive recognized-but-expired clinic session (deterministic expiresAt, no real clock) on every path getDashboardStats() loads concurrently, and redirectToLoginOnUnauthorized turns that into a real /login redirect. Additive/opt-in cookie value; the 23 existing fixture consumers keep receiving byte-identical responses. Validates the SIMULATED fixture boundary, not Fastify; E2E-GLOBAL-03B closes the authoritative one. Security boundary; do not demote." }),
  entry("e2e/platform/auth/session-boundary-forbidden-role.spec.ts", "platform", "auth", "absent/unrecognized/expired session -> 401, insufficient role -> 403 (simulated)", ["smoke"], ci, "fixture", "The fixture's /api/e2e/session-boundary probe answers 401 for absent, unrecognized and expired sessions and for a session value sent under another role's cookie, 403 for a valid clinic session on the admin-only check, and accepts a valid admin session; it mirrors no production endpoint.", { criticality: "P1", fixture: "admin-populated-api-server", notes: "E2E-GLOBAL-03 (LIMPIEZA E2E P0-1/R-01): new, additive /api/e2e/session-boundary probe on admin-populated-api-server.mjs models the explicit value->role->expiresAt table and answers 401 (absent/unrecognized/expired) and 403 (valid, non-expired clinic session on an admin-only check); mirrors no production endpoint, so it cannot affect any of the 23 existing fixture consumers. Validates the SIMULATED fixture boundary, not Fastify; E2E-GLOBAL-03B closes the authoritative one. Security boundary; do not demote." }),
  entry("e2e/platform/hydration/contacto-hydration.spec.ts", "platform", "hydration", "contact page hydration", ["smoke"], ci, "fixture", "The /contacto form inputs and textarea hydrate without mismatch, and each intent routes without changing the form contract."),
  entry("e2e/platform/hydration/login-hydration.spec.ts", "platform", "hydration", "login page hydration", ["smoke"], ci, "fixture", "/login hydrates with a deterministic CTA and clinic form controls without page or hydration console errors, and its initial state survives dev API fallback warnings."),
  entry("e2e/platform/smoke/visual-smoke.spec.ts", "platform", "smoke", "multi-surface render sanity", ["smoke"], ci, "fixture", "/, /contacto, /particulares, /login and an unauthenticated /dashboard return an OK response and render their expected text at 1440x1000 and 390x844.", { evidence: "memory" }),
  entry("e2e/platform/theme/theme-mode.spec.ts", "platform", "theme", "light dark toggle", ["smoke"], ci, "fixture", "The theme toggle switches to dark gray, persists and returns to normal, and a persisted dark gray theme applies before hydration without mismatch."),
  entry("e2e/public/clinics/public-clinics-b2b-operations.spec.ts", "public", "clinics", "B2B operations landing", ["public-clinic"], ci, "fixture", "/clinicas renders the operations steps, three product modules, onboarding, conversion CTAs toward contacto and its JSON-LD, contains no B2B wording or demo/fictitious content, calls no private API and has no horizontal overflow on mobile."),
  entry("e2e/public/home/home-hero-evidence-first.spec.ts", "public", "home", "hero evidence-first", ["public-clinic"], ci, "fixture", "The home hero shows the VETNEB H1, the professional signature, the portal and tracking CTAs, schedule and WhatsApp, no process diagram or demo data, and serves the hero image through the next/image optimizer with real dimensions."),
  entry("e2e/public/home/public-perspective-scroll.spec.ts", "public", "home", "perspective scroll", ["public-clinic"], ci, "fixture", "Public routes render perspective sections outside navbar and footer, desktop transforms change with scroll position and intensity hierarchy, sections stay readable, reduced motion disables the transforms, mobile has no horizontal overflow and the navbar still opens and closes."),
  entry("e2e/public/navigation/public-navigation-footer.spec.ts", "public", "navigation", "navigation and footer", ["public-clinic"], ci, "fixture", "The desktop navbar and footer preserve the public information architecture, mobile navigation opens and closes with its public links, public routes have no horizontal overflow per tested width, the navbar pill shows at xl and the skip control activates by keyboard."),
  entry("e2e/public/pricing/public-pricing-actionable.spec.ts", "public", "pricing", "actionable pricing", ["public-clinic"], ci, "mocked", "With a route-stubbed /api/public/pricing, /precios renders the hero CTA, dynamic categories and studies, Consultar labels for unpriced items, per-category CTAs, a skeleton while loading and a visible alert on a stubbed 500, and makes no private or auth API calls."),
  entry("e2e/public/reports/public-report-preview.spec.ts", "public", "reports", "public report preview", ["public-clinic"], ci, "fixture", "Home, /servicios and /clinicas show no demo badge, fictitious patient/case data or report preview, preserve their hero CTAs and sections, call no private API and have no mobile horizontal overflow."),
  entry("e2e/public/routes/public-routes.spec.ts", "public", "routes", "public routes resolve", ["smoke"], ci, "fixture", "Each public route renders its expected text, /particulares keeps hero, primary action and next-step zone visible without horizontal overflow on mobile with /login reachable, unknown routes render the branded not-found page and global metadata publishes one OpenGraph/Twitter image.", { criticality: "P1", notes: "Availability boundary; do not demote." }),
  entry("e2e/public/services/public-service-bento-specimen-journey.spec.ts", "public", "services", "service bento specimen journey", ["public-clinic"], ci, "fixture", "Home and /servicios render the service bento and the 5-stage specimen journey with its protocol data (formol 10%, 15 días hábiles), centered journey numbers and preserved CTAs, call no private API and have no mobile horizontal overflow."),
  entry("e2e/regression/dashboard-adaptive-limit-baseline.spec.ts", "regression", "dashboard", "adaptive limit baseline 15x13", [], extended, "mocked", "The adaptive source/limit/offset/secondPageCount of 15 consumers x 13 viewports equals the committed A03 baseline, with populated fixture sessions plus route stubs for the endpoints the fixture does not serve.", { criticality: "P1", fixture: "admin-populated-api-server", evidence: "test-results", notes: "A03: frozen CURRENT adaptive window for 15 consumers across 13 canonical viewports (195 primary records, 234 leaves); exact source/limit/offset/secondPageCount comparison, platform fail-closed." }),
  entry("e2e/regression/dashboard-b04-surface-token-migration.spec.ts", "regression", "dashboard", "persistent chrome elevation", ["visual-contract"], ci, "mocked", "The persistent chrome computes to no elevation shadow over 21 surfaces x 2 themes x 2 viewport classes; the surfaces whose endpoints the fixture answers 404 for are route-stubbed.", { criticality: "P1", fixture: "admin-populated-api-server", evidence: "test-results", notes: "B04 / audit gate G6: the persistent chrome (shell frame, topbar, horizontal nav, module rail, both mobile bottom navs, filter toolbar, sticky action bar, module tablist) must compute to no elevation shadow. Same canonical matrix owner as A02/A08 (21 surfaces) x 2 themes (normal, dark-gray) x 2 viewport classes (1366x768, 390x844) = 84 states. Transient overlays and focus rings keep their shadow by classification and are NOT asserted flat. Routed to visual-contract because AGENTS.md 7 maps the visual contract to that cohort; do not demote." }),
  entry("e2e/regression/dashboard-b05-surface-inversion.spec.ts", "regression", "dashboard", "filter-field surface inversion", ["visual-contract"], ci, "mocked", "The super searcher filter bars resolve a transparent container and a --dash-color-field tinted field in both themes; admin-clinicas data is route-stubbed and clinic-tokens is expected BLOCKED because the fixture has no /api/particular-tokens handler.", { criticality: "P1", fixture: "admin-populated-api-server", evidence: "test-results", notes: "B05: the 7 super searchers (S1-S7) must resolve a transparent filter-bar/band container and a tinted field via --dash-color-field, in both themes. SHARED surfaces (S1/S2/S3/S6/S7) test only the desktop-visible FilterBar instance — the mobile density renders inside a Radix Dialog.Portal outside .dashboard-app-shell, a pre-B05 gap out of scope to fix. DIRECT surfaces (S4/S5) test both viewport classes since their desktop/mobile markup coexists in the DOM. S7 (clinic-tokens) is expected BLOCKED: the hermetic fixture implements no /api/particular-tokens handler, so its FilterBar never mounts." }),
  entry("e2e/regression/dashboard-b06-workspace-app-bar.spec.ts", "regression", "dashboard", "workspace app bar band 21x13", ["visual-contract"], ci, "mocked", "Exactly one full-width, single-row, flat WorkspaceAppBar with one 1px rule and no overlap with main over 21 surfaces x 13 viewports, plus a dark-gray pass and the keyboard global module search; surfaces the fixture answers 404 for are route-stubbed.", { criticality: "P1", fixture: "admin-populated-api-server", evidence: "test-results", notes: "B06: the WorkspaceAppBar band over the SAME canonical matrix as A02/A08/B04 (21 surfaces x 13 viewports = 273 combinations): exactly one bar, single row, full width, no radius, no elevation, one 1px bottom rule, no overlap with main and no document scroll. Height band has two regimes: >=768px asserts the audit target 56 +/-2 px; <768px asserts the shipped admin/clinic mobile app-bar tokens, because raising them re-pages the A03-frozen phone canvases (0.672px of slack) and belongs to B09. Document/body/main scroll is NOT re-asserted here: A08 owns it over the identical matrix. Plus a dark-gray pass on 2 viewport classes (the matrix itself runs the normal theme, asserted) and the keyboard-only global module search. Routed to visual-contract because AGENTS.md 7 maps the visual contract to that cohort; do not demote." }),
  entry("e2e/regression/dashboard-b08-navigation-migration.spec.ts", "regression", "dashboard/navigation", "lateral navigation migration", ["visual-contract"], ci, "mocked", "One lateral navigation model per width regime with its band widths and item heights, no horizontal navigation, admin/clinic deep links, click, reload, Back/Forward, the admin hub null state, the five clinic full routes and a dark-gray sample; role surfaces the fixture answers 404 for are route-stubbed.", { criticality: "P1", fixture: "admin-populated-api-server", evidence: "test-results", notes: "B08: the runtime half of the navigation migration. One representative per canonical shell type (derived from the A02 matrix, fail-closed in beforeAll) across 7 breakpoint probes — 6 canonical viewports plus the local 1279px rail-regime edge, which the shared matrix has no viewport for. Asserts exactly one lateral model per regime (rail 80±1px 768-1279, drawer 256±1px >=1280, neither <768), item heights 56/40px, and the two ASYMMETRIC retirements: the horizontal nav must not exist at any viewport, while the legacy clinic module rail must be hidden >=768px and STILL VISIBLE <768px, because ClinicMobileBottomNav returns null on /dashboard and B09 owns its replacement. Plus admin/clinic deep links, click, reload, Back/Forward, the admin hub null state, the five clinic full routes, and a dark-gray sample. Re-checks only the four frame invariants a lateral band can break (document/main scroll, horizontal overflow, app-bar band and overlap); A08 and B06 keep ownership over the full 21x13 matrix. Routed to visual-contract because AGENTS.md §7 maps the visual/zero-scroll contract to that cohort; do not demote." }),
  entry("e2e/regression/dashboard-b09-mobile-navigation-unification.spec.ts", "regression", "dashboard/navigation", "mobile navigation unification", ["visual-contract"], ci, "fixture", "With populated fixture sessions, exactly one mobile navigation owner below 768px and none at 768px, the retired rail absent, the admin primary cut with overflow reachability, the five clinic direct slots, deep links, history, hub reset, ?module= convergence and measured >=44x44 touch targets.", { criticality: "P1", fixture: "admin-populated-api-server", evidence: "test-results", notes: "B09: the runtime half of the mobile navigation unification. Four owners became one (AdminMobileBottomNav + AdminMobileModuleMenu + ClinicMobileBottomNav + DashboardModuleRail -> DashboardMobileNav), which closes the LEGACY_MODULE_RAIL_PHYSICAL_RETIREMENT deferral B08 left: the clinic bottom nav returned null on /dashboard, so the rail was that surface's only phone navigation. Asserts exactly one visible owner below 768px on 4 surfaces x 2 phone viewports and none at the 768px boundary, the retired rail absent at every viewport, admin's curated primary cut plus whole-catalog overflow reachability, clinic's five slots with neither Inicio nor overflow (B09_CLINIC_HOME_ITEM = RETIRED, CLINIC_MOBILE_OVERFLOW = RETIRED: the whole clinic catalog is promoted, so every module is a direct slot and reports aria-current on itself) sized across 320/360/375/390/412/430 plus a keyboard sweep of the five, and the module every clinic surface marks current, deep links, Back/Forward, reload, hub reset, the unknown and aliased ?module= convergence the retired raw read got wrong, and MEASURED >=44x44 touch targets on every control B09 owns plus the 48px admin app bar (B09_TOUCH_POLICY = OPTION_A, B09_ADMIN_MOBILE_APPBAR_H = 48px). Zero-scroll and the app-bar band over the full 21x13 matrix stay owned by A08 and B06. Routed to visual-contract because AGENTS.md 7 maps the visual/zero-scroll contract to that cohort; do not demote." }),
  entry("e2e/regression/dashboard-b10-clinic-shell-unification.spec.ts", "regression", "dashboard/shell", "clinic app shell unification", ["visual-contract"], ci, "mocked", "The six clinic routes each render exactly one app bar, one lateral band and one main with an unchanged stage structure across mobile/rail/drawer probes, and deep links, reload, Back/Forward and the declared active module survive; clinic surfaces the fixture answers 404 for are route-stubbed.", { criticality: "P1", fixture: "admin-populated-api-server", evidence: "test-results", notes: "B10: the runtime half of the clinic app-shell unification. B08 and B09 had already retired the two bands P0-04 measured, so the six clinic routes no longer differed in chrome — they differed in who DECLARED it. ClinicDashboardShell is now the single owner of DashboardTopbar + DashboardNavigationFrame + main.dashboard-main, and this spec asserts the resulting EQUIVALENCE: exactly one app bar, one lateral band and one main per route across three probe viewports (mobile/rail/drawer), main's direct-child count and first child unchanged, main still a direct child of the frame, the logistics reservation root still main itself and the sticky action bar still its DIRECT child (zero-scroll.css reads it with :has(> …)), plus deep links, reload, Back/Forward and the declared active module reaching the lateral band. The five full routes are DERIVED from the A02 matrix by shellType and the viewports taken by slug, fail-closed in beforeAll, so a surface added there cannot escape. Also pins what became of the PRESERVED B09 behaviour it fenced: the bar used to mark Inicio on a full route, and now marks that route's own module, because Clinica retired the Inicio slot (B09_CLINIC_HOME_ITEM = RETIRED). Zero-scroll over the full 21x13 matrix stays owned by A08 and the app-bar band by B06. Routed to visual-contract because AGENTS.md §7 maps the visual/zero-scroll contract to that cohort; do not demote." }),
  entry("e2e/regression/dashboard-b11-workspace-header.spec.ts", "regression", "dashboard", "workspace header 40px", ["visual-contract"], ci, "fixture", "On admin-tokens and clinic-tokens with populated fixture sessions (neither surface is stubbed), the shared WorkspaceHeader is 40 +/-2px with 16px inline padding, flat and title-sm, with aria-describedby copy outside the flow, one app shell, preserved mobile navigation, deep links and outer zero-scroll.", { criticality: "P1", fixture: "admin-populated-api-server", evidence: "test-results", notes: "B11: canonical WorkspaceHeader shared by the two DashboardModuleWorkspace consumers. Proves 40 +/-2px, 16px inline padding, flat geometry, title-sm typography, programmatic aria-describedby copy outside permanent flow, one app shell, preserved B09 admin-mobile reclaim and clinic mobile navigation, deep links and exact A08 outer zero-scroll on representative mobile/desktop surfaces. A02 keeps the full geometry matrix and A03 the full adaptive limit matrix." }),
  entry("e2e/regression/dashboard-b12-module-card-removal.spec.ts", "regression", "dashboard", "module card removal", ["visual-contract"], ci, "mocked", "The six audited admin collection modules paint no intermediate module card while the other nine module workspaces own none, preserving 1px geometry, the B11 header, deep links and outer zero-scroll; the module surfaces the fixture answers 404 for are route-stubbed.", { criticality: "P1", fixture: "admin-populated-api-server", evidence: "test-results", notes: "B12: removes only the explicitly marked intermediate module-card paint for six audited admin collection modules. The other nine module workspaces have owner count 0. It preserves 1px box geometry, B11 header, deep links and A08 outer zero-scroll while nested alert, panel, list and state surfaces remain outside the positive owner." }),
  entry("e2e/regression/dashboard-b13-admin-entry.spec.ts", "regression", "dashboard/navigation", "durable admin entry", ["visual-contract"], ci, "fixture", "With the populated fixture admin session, admin entry honors URL module precedence, explicit ?hub=1, the legacy invalid-module hub, bare-entry replace to a persisted or default module, storage failure fallback, Inicio persistence, reload stability and Back history.", { criticality: "P1", fixture: "admin-populated-api-server", evidence: "test-results", notes: "B13: URL module precedence, explicit ?hub=1, legacy invalid-module hub, bare-entry replace to a valid persisted module or explicit admin default, storage failure fallback, desktop and mobile Inicio persistence, reload stability and Back history." }),
  entry("e2e/regression/dashboard-b14-metrics-relocation.spec.ts", "regression", "dashboard", "metrics relocation", ["admin-mobile"], ci, "mocked", "The five audited metric strips render inside existing headers or functional toolbars on clinic-operaciones and admin tokens, sesiones, usuarios and auditoría; admin-sesiones data is route-stubbed.", { criticality: "P1", fixture: "admin-populated-api-server", evidence: "test-results", notes: "B14: five audited metric strips move into existing headers or functional toolbars without changing the 15-module navigation census. The clinic command center leaves metric ownership to its Métricas tab; the audit mobile summary shares the existing filters toolbar. A03 keeps adaptive capacity ownership and is revalidated separately only for audit, users and sessions." }),
  entry("e2e/regression/dashboard-geometry-baseline.spec.ts", "regression", "dashboard", "geometry baseline 21x13", [], extended, "mocked", "The current geometry of 21 surfaces x 13 viewports equals the committed A02 baseline; the five surfaces the fixture answers 404 for are route-stubbed.", { criticality: "P1", fixture: "admin-populated-api-server", evidence: "test-results", notes: "A02: frozen CURRENT geometry of 21 surfaces x 13 viewports (273 combinations); not target geometry (audit §46), not the A08 zero-scroll contract." }),
  entry("e2e/regression/dashboard-limit-invariance.spec.ts", "regression", "dashboard", "A05 stable geometry reservation limit invariance 15x13", [], extended, "mocked", "15 adaptive consumers x 13 viewports keep exact 32/48/64px internal-region limit invariance and survive hot A-B-A viewport transitions, on fixture sessions plus the same route stubs as A03.", { criticality: "P1", fixture: "admin-populated-api-server", notes: "A05: 15 adaptive consumers across the 13 canonical viewports; exact 32/48/64 internal-region invariance plus hot A-B-A viewport transitions." }),
  entry("e2e/regression/dashboard-operational-contract.spec.ts", "regression", "dashboard", "operational contract S1", ["smoke"], ci, "fixture", "With a synthetic admin session cookie, the S1 audit super searcher keeps its URL-persisted filter contract; S2-S7 are covered by a source-backed unit test, not by this spec.", { criticality: "P1", notes: "A01: this E2E covers S1 (the only URL-persisted super searcher); the source-backed matrix in test/unit/ui/dashboard/dashboard-operational-contract-baseline.test.ts covers S1-S7." }),
  entry("e2e/regression/dashboard-zero-scroll-baseline.spec.ts", "regression", "dashboard", "zero-scroll baseline 21x13", ["visual-contract"], ci, "mocked", "documentElement, body and main.dashboard-main do not scroll (exact 0px) and main is not an operational scroll container over 21 surfaces x 13 viewports; the five surfaces the fixture answers 404 for are route-stubbed.", { criticality: "P1", fixture: "admin-populated-api-server", evidence: "test-results", notes: "A08: app-shell zero-scroll freeze over the SAME canonical A02 matrix (21 surfaces x 13 viewports = 273 combinations); documentElement/body/main.dashboard-main must not scroll (exact 0px) and main must not be an operational scroll container. Contracted internal canvas scroll stays permitted (audit §10). Routed to visual-contract because AGENTS.md §7 maps the zero-scroll/visual contract to that cohort and §10 names it the exit criterion; do not demote." }),
  entry("e2e/regression/evidence/dashboard-runtime-post-ux1-visual-evidence.spec.ts", "regression", "evidence", "runtime visual evidence", [], evidence, "mocked", "Evidence generator: captures post-UX1 dashboard screenshots at mobile and desktop viewports with a synthetic clinic session and a route-stubbed /api/clinic/profile, with layout expectations but no baseline comparison.", { evidence: "test-results" }),
  entry("e2e/regression/evidence/remove-home-unified-workspace-screenshots.spec.ts", "regression", "evidence", "workspace screenshots evidence", [], evidence, "fixture", "Evidence generator only: writes /dashboard screenshots per viewport with a synthetic clinic session to the Playwright output dir; it makes no assertions.", { evidence: "test-results" }),
  entry("e2e/regression/visual/visual-regression-authenticated.spec.ts", "regression", "visual", "authenticated dual-theme pixel baseline", [], visualLinux, "fixture", "Pixel comparison of 2 authenticated routes x 5 viewports x 2 themes against 20 committed Chromium-Linux baselines, with populated fixture sessions.", { platform: "linux", evidence: "snapshots", targetGate: "manual", notes: "R9: dual since B04 - 2 routes x 5 viewports x 2 themes = 20 Chromium-Linux baselines. The 10 normal names are unchanged from before B04; the dark set carries a -dark-gray suffix." }),
  entry("e2e/regression/visual/visual-regression-public.spec.ts", "regression", "visual", "public pixel baseline", [], visualLinux, "fixture", "Pixel comparison of public routes against committed Chromium-Linux baselines.", { platform: "linux", evidence: "snapshots", targetGate: "manual", notes: "Linux-only baseline; public spec has no platform skip." }),
  entry("e2e/regression/visual/visual-regression-stress.spec.ts", "regression", "visual", "stress pixel baseline", [], visualLinux, "mocked", "Pixel comparison of authenticated stress states against committed Chromium-Linux baselines, with a catch-all route stub on /api/** serving the stress datasets.", { platform: "linux", evidence: "snapshots", targetGate: "manual" }),
] as const satisfies readonly E2eCatalogEntry[];

export const E2E_MANUAL_ONLY_SPECS = [] as const satisfies readonly `e2e/${string}.spec.ts`[];

export const E2E_COHORT_SPECS: Readonly<Record<E2eExecutionCohort, readonly E2eCatalogEntry["path"][]>> =
  Object.freeze({
    ci: E2E_SUITE_CATALOG.filter((item) => item.executionCohorts.includes("ci")).map((item) => item.path),
    extended: E2E_SUITE_CATALOG.filter((item) => item.executionCohorts.includes("extended")).map((item) => item.path),
    evidence: E2E_SUITE_CATALOG.filter((item) => item.executionCohorts.includes("evidence")).map((item) => item.path),
    "visual-linux": E2E_SUITE_CATALOG.filter((item) => item.executionCohorts.includes("visual-linux")).map((item) => item.path),
    full: E2E_SUITE_CATALOG.filter((item) => item.executionCohorts.includes("full")).map((item) => item.path),
    affected: [],
  });

export const E2E_CURRENT_COHORT_SPECS: Readonly<Record<E2eCurrentCohort, readonly E2eCatalogEntry["path"][]>> =
  Object.freeze({
    smoke: E2E_SUITE_CATALOG.filter((item) => item.currentCohorts.includes("smoke")).map((item) => item.path),
    "admin-mobile": E2E_SUITE_CATALOG.filter((item) => item.currentCohorts.includes("admin-mobile")).map((item) => item.path),
    "visual-contract": E2E_SUITE_CATALOG.filter((item) => item.currentCohorts.includes("visual-contract")).map((item) => item.path),
    "public-clinic": E2E_SUITE_CATALOG.filter((item) => item.currentCohorts.includes("public-clinic")).map((item) => item.path),
  });
